import Link from "next/link";
import { CheckCircle2, Clock3, Download, FileCog, FileText, XCircle } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { ContractWorkflow } from "@/components/contracts/contract-workflow";
import { generateContractDocumentAction, updateReservationStatusAction } from "@/app/contracts/actions";
import { requireDormitoryContext } from "@/lib/auth/context";
import { relationOne } from "@/lib/supabase/relations";

const reservationLabels: Record<string, string> = { pending_payment: "รอชำระเงินจอง", confirmed: "ยืนยันแล้ว", cancelled: "ยกเลิก", expired: "หมดอายุ", converted: "ทำสัญญาแล้ว" };
const date = (value: string) => new Intl.DateTimeFormat("th-TH", { dateStyle: "medium", timeZone: "Asia/Bangkok" }).format(new Date(value));
const money = (value: string | number) => new Intl.NumberFormat("th-TH", { style: "currency", currency: "THB" }).format(Number(value));

export default async function ContractsPage() {
  const context = await requireDormitoryContext("contracts.manage");
  const [{ data: rooms }, { data: tenants }, { data: reservations }, { data: contracts }, { data: documents }] = await Promise.all([
    context.supabase.from("rooms").select("id,room_number,monthly_rent,status,room_types(deposit)").eq("dormitory_id", context.dormitoryId).in("status", ["vacant", "reserved"]).is("deleted_at", null).order("room_number"),
    context.supabase.from("tenants").select("id,tenant_code,title,first_name,last_name").eq("dormitory_id", context.dormitoryId).eq("status", "active").is("deleted_at", null).order("first_name"),
    context.supabase.from("reservations").select("id,reservation_number,room_id,tenant_id,expected_move_in_date,booking_amount,status,expires_at,rooms(room_number),tenants(first_name,last_name)").eq("dormitory_id", context.dormitoryId).order("created_at", { ascending: false }).limit(50),
    context.supabase.from("contracts").select("id,contract_number,start_date,end_date,monthly_rent,status,rooms(room_number),tenants(first_name,last_name)").eq("dormitory_id", context.dormitoryId).order("created_at", { ascending: false }).limit(50),
    context.supabase.from("generated_documents").select("id,entity_id").eq("dormitory_id", context.dormitoryId).eq("document_type", "contract"),
  ]);
  const roomOptions = (rooms ?? []).map((room) => ({ id: room.id, roomNumber: room.room_number, monthlyRent: String(room.monthly_rent), deposit: String(relationOne(room.room_types)?.deposit ?? "0.00"), status: room.status }));
  const tenantOptions = (tenants ?? []).map((tenant) => ({ id: tenant.id, label: `${tenant.tenant_code} · ${tenant.title ?? ""}${tenant.first_name} ${tenant.last_name}` }));
  const confirmedReservations = (reservations ?? []).filter((item) => item.status === "confirmed").map((item) => ({ id: item.id, roomId: item.room_id, tenantId: item.tenant_id, label: `${item.reservation_number} · ห้อง ${relationOne(item.rooms)?.room_number} · ${relationOne(item.tenants)?.first_name} ${relationOne(item.tenants)?.last_name}` }));
  const documentByContract = new Map((documents ?? []).map((item) => [item.entity_id, item.id]));
  return <AppShell><div className="mx-auto max-w-7xl p-4 md:p-8"><header className="mb-6 flex flex-wrap items-end justify-between gap-3"><div><p className="text-sm font-semibold text-teal-700">RESERVATION & CONTRACT</p><h1 className="text-2xl font-bold">การจอง สัญญา และย้ายเข้า</h1><p className="text-sm text-[var(--muted)]">{context.dormitoryName} · ทุกขั้นตอนบันทึก Audit Log และล็อกห้องในฐานข้อมูล</p></div><Link href="/contracts/templates" className="flex items-center gap-2 rounded-lg border border-slate-300 bg-[var(--surface)] px-4 py-2 text-sm"><FileCog size={17}/>ตั้งค่า Template</Link></header>
    <ContractWorkflow rooms={roomOptions} tenants={tenantOptions} confirmedReservations={confirmedReservations}/>
    <div className="mt-6 grid items-start gap-5 xl:grid-cols-2"><section className="rounded-xl border border-slate-200 bg-[var(--surface)]"><div className="border-b border-slate-200 p-4"><h2 className="font-bold">รายการจองล่าสุด</h2></div>{!reservations?.length ? <p className="p-8 text-center text-[var(--muted)]">ยังไม่มีรายการจอง</p> : <div className="divide-y divide-slate-100">{reservations.map((item) => <article key={item.id} className="p-4"><div className="flex flex-wrap items-start justify-between gap-2"><div><p className="font-semibold">{item.reservation_number} · ห้อง {relationOne(item.rooms)?.room_number}</p><p className="text-sm text-[var(--muted)]">{relationOne(item.tenants)?.first_name} {relationOne(item.tenants)?.last_name} · เข้าอยู่ {date(item.expected_move_in_date)}</p><p className="text-sm">เงินจอง {money(item.booking_amount)}</p></div><span className={`rounded-full px-2.5 py-1 text-xs ${item.status === "confirmed" ? "bg-emerald-50 text-emerald-700" : item.status === "pending_payment" ? "bg-amber-50 text-amber-700" : "bg-slate-100 text-slate-600"}`}>{reservationLabels[item.status] ?? item.status}</span></div>{item.status === "pending_payment" && <div className="mt-3 flex gap-2"><form action={updateReservationStatusAction}><input type="hidden" name="reservationId" value={item.id}/><input type="hidden" name="status" value="confirmed"/><button className="flex items-center gap-1 rounded-lg bg-emerald-700 px-3 py-1.5 text-xs text-white"><CheckCircle2 size={14}/>ยืนยันการจอง</button></form><form action={updateReservationStatusAction}><input type="hidden" name="reservationId" value={item.id}/><input type="hidden" name="status" value="cancelled"/><input type="hidden" name="reason" value="ยกเลิกโดยเจ้าหน้าที่"/><button className="flex items-center gap-1 rounded-lg border border-red-200 px-3 py-1.5 text-xs text-red-700"><XCircle size={14}/>ยกเลิก</button></form></div>}{item.status === "confirmed" && <form action={updateReservationStatusAction} className="mt-3"><input type="hidden" name="reservationId" value={item.id}/><input type="hidden" name="status" value="cancelled"/><input type="hidden" name="reason" value="ยกเลิกโดยเจ้าหน้าที่"/><button className="flex items-center gap-1 rounded-lg border border-red-200 px-3 py-1.5 text-xs text-red-700"><XCircle size={14}/>ยกเลิกการจอง</button></form>}</article>)}</div>}</section>
      <section className="rounded-xl border border-slate-200 bg-[var(--surface)]"><div className="border-b border-slate-200 p-4"><h2 className="font-bold">สัญญาล่าสุด</h2></div>{!contracts?.length ? <p className="p-8 text-center text-[var(--muted)]">ยังไม่มีสัญญา</p> : <div className="divide-y divide-slate-100">{contracts.map((item) => { const documentId = documentByContract.get(item.id); return <article key={item.id} className="p-4"><div><Link href={`/contracts/${item.id}`} className="font-semibold text-teal-800 hover:underline">{item.contract_number} · ห้อง {relationOne(item.rooms)?.room_number}</Link><p className="text-sm text-[var(--muted)]">{relationOne(item.tenants)?.first_name} {relationOne(item.tenants)?.last_name}</p><p className="mt-1 flex items-center gap-1 text-xs text-[var(--muted)]"><Clock3 size={13}/>{date(item.start_date)} – {date(item.end_date)} · {money(item.monthly_rent)}/เดือน</p></div><div className="mt-3 flex flex-wrap gap-2"><Link href={`/contracts/${item.id}`} className="flex items-center gap-1 rounded-lg border border-teal-300 px-3 py-1.5 text-xs text-teal-800"><FileText size={14}/>ตรวจรับ/ลงนาม</Link><Link href={`/contracts/${item.id}/print`} target="_blank" className="flex items-center gap-1 rounded-lg border border-slate-300 px-3 py-1.5 text-xs"><FileText size={14}/>พิมพ์ HTML</Link>{documentId ? <Link href={`/api/documents/${documentId}/pdf`} className="flex items-center gap-1 rounded-lg bg-teal-700 px-3 py-1.5 text-xs text-white"><Download size={14}/>ดาวน์โหลด PDF</Link> : <form action={generateContractDocumentAction}><input type="hidden" name="contractId" value={item.id}/><button className="flex items-center gap-1 rounded-lg bg-teal-700 px-3 py-1.5 text-xs text-white"><FileText size={14}/>สร้าง PDF Snapshot</button></form>}</div></article>;})}</div>}</section></div>
  </div></AppShell>;
}
