import { z } from "zod";

const decimal3=z.string().trim().regex(/^\d{1,12}(\.\d{1,3})?$/,"กรุณาระบุตัวเลขไม่เกิน 3 ตำแหน่ง");
const money4=z.string().trim().regex(/^\d{1,10}(\.\d{1,4})?$/,"กรุณารบุราคาให้ถูกต้อง");
export const createMeterSchema=z.object({roomId:z.string().uuid(),meterType:z.enum(["water","electricity","other"]),meterNumber:z.string().trim().min(2).max(50),initialReading:decimal3,rolloverMax:z.string().trim().optional().default(""),notes:z.string().trim().max(500).optional().default("")}).superRefine((v,c)=>{if(v.rolloverMax&&!decimal3.safeParse(v.rolloverMax).success)c.addIssue({code:"custom",path:["rolloverMax"],message:"ค่าสูงสุดไม่ถูกต้อง"});});
export const meterReadingSchema=z.object({meterId:z.string().uuid(),billingMonth:z.string().regex(/^\d{4}-\d{2}-01$/),currentReading:decimal3,meterReplaced:z.preprocess(v=>v==="on",z.boolean()),meterRollover:z.preprocess(v=>v==="on",z.boolean()),notes:z.string().trim().max(500).optional().default("")}).refine(v=>!(v.meterReplaced&&v.meterRollover),{path:["meterReplaced"],message:"เลือกเปลี่ยนมิเตอร์หรือมิเตอร์วนรอบอย่างใดอย่างหนึ่ง"});
const tier=z.object({fromUnit:decimal3,toUnit:z.union([decimal3,z.null()]),pricePerUnit:money4});
export const ratePlanSchema=z.object({name:z.string().trim().min(2).max(100),meterType:z.enum(["water","electricity","other"]),pricingType:z.enum(["fixed","tiered"]),pricePerUnit:z.string().trim().optional().default(""),minimumCharge:money4,effectiveFrom:z.string().date(),tiersJson:z.string().trim().optional().default("[]")}).superRefine((v,c)=>{if(v.pricingType==="fixed"&&!money4.safeParse(v.pricePerUnit).success)c.addIssue({code:"custom",path:["pricePerUnit"],message:"กรุณาระบุราคาต่อหน่วย"});if(v.pricingType==="tiered"){try{const parsed=z.array(tier).min(1).parse(JSON.parse(v.tiersJson));let expected="0";parsed.forEach((item,index)=>{if(Number(item.fromUnit)!==Number(expected))c.addIssue({code:"custom",path:["tiersJson"],message:`ขั้นที่ ${index+1} ต้องเริ่มต่อจากขั้นก่อนหน้า`});expected=item.toUnit??"END";});if(expected!=="END")c.addIssue({code:"custom",path:["tiersJson"],message:"ขั้นสุดท้ายต้องกำหนด toUnit เป็น null"});}catch{c.addIssue({code:"custom",path:["tiersJson"],message:"รูปแบบขั้นบันไดไม่ถูกต้อง"});}}});
export type MeterActionState={success?:boolean;message?:string;error?:string;fieldErrors?:Record<string,string[]|undefined>};
