import{createHash}from"node:crypto";import{NextResponse}from"next/server";import{lineWebhookSecret}from"@/lib/env";import{createLineAdapter}from"@/lib/line/adapter";import{invoiceFlexMessage}from"@/lib/line/flex";import{verifyLineSignature}from"@/lib/line/signature";import type{LineMessage,LineWebhookEvent,LineWebhookPayload}from"@/lib/line/types";import{createSupabaseAdminClient}from"@/lib/supabase/admin";import{relationOne}from"@/lib/supabase/relations";import{LineMessagingService}from"@/services/line-messaging-service";
export const runtime="nodejs";
const knownCommands:Record<string,string>={"บิล":"bill","ยอดค้าง":"bill","ชำระเงิน":"payment","แจ้งซ่อม":"maintenance","ติดต่อเจ้าหน้าที่":"contact"};
const text=(value:string):LineMessage=>({type:"text",text:value});
async function latestInvoiceMessage(db:ReturnType<typeof createSupabaseAdminClient>,account:{dormitory_id:string;tenant_id:string},appUrl:string){const{data}=await db.from("invoices").select("id,invoice_number,due_date,total,balance,status,billing_cycles(billing_month),rooms(room_number),dormitories(name),invoice_items(description,line_total)").eq("dormitory_id",account.dormitory_id).eq("tenant_id",account.tenant_id).not("status","in",'(cancelled,written_off)').order("issue_date",{ascending:false}).limit(1).maybeSingle();if(!data)return text("ยังไม่พบใบแจ้งหนี้ของคุณในระบบ");const cycle=relationOne(data.billing_cycles);const room=relationOne(data.rooms);const dorm=relationOne(data.dormitories);return invoiceFlexMessage({dormitory:dorm?.name??"หอพัก",room:room?.room_number??"—",invoiceNumber:data.invoice_number,billingMonth:cycle?.billing_month??"—",dueDate:data.due_date,total:String(data.total),balance:String(data.balance),status:data.status,items:(data.invoice_items??[]).map(i=>({description:i.description,amount:String(i.line_total)})),appUrl,invoiceId:data.id});}
async function processEvent(event:LineWebhookEvent,index:number,rawBody:string){const db=createSupabaseAdminClient();const eventId=event.webhookEventId??createHash("sha256").update(`${rawBody}:${index}`).digest("hex");const sourceUser=event.source?.userId??null;const existing=await db.from("line_webhook_events").select("id,processing_status").eq("webhook_event_id",eventId).maybeSingle();if(existing.data?.processing_status==="processed"||existing.data?.processing_status==="ignored")return"duplicate";if(!existing.data){const inserted=await db.from("line_webhook_events").insert({webhook_event_id:eventId,event_type:event.type??"unknown",source_line_user_id:sourceUser,message_type:event.message?.type??null,event_timestamp:event.timestamp?new Date(event.timestamp).toISOString():null}).select("id").single();if(inserted.error&&inserted.error.code==="23505")return"duplicate";if(inserted.error)throw inserted.error;}
  const{data:account}=sourceUser?await db.from("line_accounts").select("id,organization_id,dormitory_id,tenant_id,line_user_id,status").eq("line_user_id",sourceUser).maybeSingle():{data:null};if(account)await db.from("line_webhook_events").update({organization_id:account.organization_id,dormitory_id:account.dormitory_id}).eq("webhook_event_id",eventId);
  try{if(event.type==="unfollow"){if(account)await db.from("line_accounts").update({status:"blocked",updated_at:new Date().toISOString()}).eq("id",account.id);await db.from("line_webhook_events").update({processing_status:"processed",processed_at:new Date().toISOString()}).eq("webhook_event_id",eventId);return"processed";}
    if(!event.replyToken){await db.from("line_webhook_events").update({processing_status:"ignored",processed_at:new Date().toISOString()}).eq("webhook_event_id",eventId);return"ignored";}
    let message:LineMessage;let command:string|undefined;if(event.type==="follow")message=text(account?"เชื่อมบัญชีผู้เช่าแล้ว พิมพ์ “บิล” เพื่อดูยอดล่าสุด":"ยินดีต้อนรับ กรุณากดเมนู “เชื่อมบัญชีผู้เช่า” และกรอกรหัสเชื่อมต่อจากหอพัก");else if(event.type==="message"&&event.message?.type==="text"){const normalized=(event.message.text??"").trim();command=knownCommands[normalized];if(!account)message=text("ยังไม่ได้เชื่อมบัญชีผู้เช่า กรุณาขอรหัสเชื่อมต่อจากเจ้าหน้าที่");else if(command==="bill")message=await latestInvoiceMessage(db,account,process.env.APP_URL??process.env.NEXT_PUBLIC_APP_URL??"http://localhost:3000");else if(command==="payment")message=text(`แจ้งชำระเงินได้ที่ ${(process.env.APP_URL??process.env.NEXT_PUBLIC_APP_URL??"http://localhost:3000")}/payments`);else if(command==="maintenance")message=text("รับทราบคำขอแจ้งซ่อม กรุณาระบุรายละเอียดและรูปภาพผ่านเมนูแจ้งซ่อม (ระบบฟอร์มผู้เช่ากำลังเชื่อมต่อ)");else if(command==="contact")message=text("เจ้าหน้าที่จะติดต่อกลับในเวลาทำการ กรุณาพิมพ์รายละเอียดที่ต้องการติดต่อ");else message=text("เมนูช่วยเหลือ\n• พิมพ์ บิล หรือ ยอดค้าง\n• พิมพ์ ชำระเงิน\n• พิมพ์ แจ้งซ่อม\n• พิมพ์ ติดต่อเจ้าหน้าที่");}else message=text("กรุณาใช้เมนูข้อความเพื่อดูบิล ชำระเงิน แจ้งซ่อม หรือติดต่อเจ้าหน้าที่");
    if(command)await db.from("line_webhook_events").update({command_name:command}).eq("webhook_event_id",eventId);
    if(account){await new LineMessagingService().reply(account,event.replyToken,[message],{messageType:command?`auto_reply_${command}`:"auto_reply_help",idempotencyKey:`webhook:${eventId}:reply`});await db.from("line_accounts").update({last_interaction_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",account.id);}else await createLineAdapter().reply(event.replyToken,[message]);
    await db.from("line_webhook_events").update({processing_status:"processed",processed_at:new Date().toISOString(),error_code:null}).eq("webhook_event_id",eventId);return"processed";
  }catch(error){await db.from("line_webhook_events").update({processing_status:"failed",error_code:error instanceof Error?error.message.slice(0,100):"PROCESSING_FAILED"}).eq("webhook_event_id",eventId);throw error;}}
export async function POST(request:Request){let secret:string;try{secret=lineWebhookSecret();}catch{return NextResponse.json({code:"LINE_NOT_CONFIGURED"},{status:503});}const rawBody=await request.text();if(!verifyLineSignature(rawBody,request.headers.get("x-line-signature"),secret))return NextResponse.json({code:"INVALID_SIGNATURE"},{status:401});let payload:LineWebhookPayload;try{payload=JSON.parse(rawBody)as LineWebhookPayload;}catch{return NextResponse.json({code:"INVALID_JSON"},{status:400});}const events=Array.isArray(payload.events)?payload.events.slice(0,50):[];const results:string[]=[];for(const[eventIndex,event]of events.entries()){try{results.push(await processEvent(event,eventIndex,rawBody));}catch{results.push("failed");}}return NextResponse.json({accepted:true,events:events.length,processed:results.filter(x=>x==="processed").length,duplicates:results.filter(x=>x==="duplicate").length},{status:200});}
