import { Search, Users } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { TenantForm } from "@/components/tenants/tenant-form";
import { requireDormitoryContext } from "@/lib/auth/context";
import { maskIdentity } from "@/lib/security/pii";

export default async function TenantsPage({searchParams}:{searchParams:Promise<{q?:string}>}) {
  const context=await requireDormitoryContext("tenants.read");
  const rawQuery=(await searchParams).q?.trim()??"";
  const query=rawQuery.replace(/[,%().]/g,"").slice(0,80);
  let request=context.supabase.from("tenants").select("id,tenant_code,title,first_name,last_name,nickname,phone,email,id_type,national_id_last4,status,created_at").eq("dormitory_id",context.dormitoryId).is("deleted_at",null).order("created_at",{ascending:false}).limit(100);
  if(query) request=request.or(`tenant_code.ilike.%${query}%,first_name.ilike.%${query}%,last_name.ilike.%${query}%,phone.ilike.%${query}%`);
  const {data:tenants,error}=await request;
  return <AppShell><div className="mx-auto max-w-7xl p-4 md:p-8"><header className="mb-6"><p className="text-sm font-semibold text-teal-700">TENANT MANAGEMENT</p><h1 className="text-2xl font-bold">ข้อมูลผู้เช่า</h1><p className="text-sm text-[var(--muted)]">{context.dormitoryName} · ข้อมูลสำคัญถูก Mask ตามสิทธิ์</p></header><div className="grid items-start gap-5 xl:grid-cols-[430px_1fr]"><TenantForm/><section><form className="mb-4 flex gap-2"><label className="relative flex-1"><Search size={18} className="absolute left-3 top-3 text-slate-400"/><input name="q" defaultValue={rawQuery} placeholder="ค้นหารหัส ชื่อ นามสกุล หรือเบอร์โทร" className="w-full rounded-lg border border-slate-300 bg-[var(--surface)] py-2.5 pl-10 pr-3"/></label><button className="rounded-lg border border-slate-300 bg-[var(--surface)] px-4">ค้นหา</button></form>{error?<div className="rounded-xl bg-red-50 p-5 text-red-700">ไม่สามารถโหลดข้อมูลผู้เช่าได้</div>:!tenants?.length?<div className="rounded-xl border border-dashed border-slate-300 p-10 text-center"><Users className="mx-auto mb-3 text-slate-400"/><p className="text-[var(--muted)]">{query?"ไม่พบผู้เช่าที่ค้นหา":"ยังไม่มีข้อมูลผู้เช่า"}</p></div>:<div className="overflow-x-auto rounded-xl border border-slate-200 bg-[var(--surface)]"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-b border-slate-200 bg-slate-50 text-slate-600"><tr><th className="p-3">รหัส</th><th className="p-3">ชื่อผู้เช่า</th><th className="p-3">ติดต่อ</th><th className="p-3">เลขเอกสาร</th><th className="p-3">สถานะ</th></tr></thead><tbody>{tenants.map(tenant=><tr key={tenant.id} className="border-b border-slate-100 last:border-0"><td className="p-3 font-mono text-xs">{tenant.tenant_code}</td><td className="p-3"><p className="font-semibold">{tenant.title} {tenant.first_name} {tenant.last_name}</p>{tenant.nickname&&<p className="text-xs text-[var(--muted)]">ชื่อเล่น {tenant.nickname}</p>}</td><td className="p-3"><p>{tenant.phone}</p><p className="text-xs text-[var(--muted)]">{tenant.email||"—"}</p></td><td className="p-3 font-mono text-xs">{maskIdentity(tenant.national_id_last4)}</td><td className="p-3"><span className="rounded-full bg-emerald-50 px-2 py-1 text-xs text-emerald-700">{tenant.status==="active"?"ใช้งาน":"ไม่ใช้งาน"}</span></td></tr>)}</tbody></table></div>}</section></div></div></AppShell>;
}
