"use server";
import{revalidatePath}from"next/cache";import{assignChargeSchema,billingCycleSchema,entityIdSchema,serviceChargeSchema,type BillingActionState}from"@/features/billing/schemas";import{requireDormitoryContext}from"@/lib/auth/context";import{BillingService}from"@/services/billing-service";
const failure=(error:unknown):BillingActionState=>{const message=error instanceof Error?error.message:"UNKNOWN";const thai=message.includes("billing_cycles_dormitory_id_billing_month_key")?"มีรอบบิลเดือนนี้แล้ว":message.includes("service_charge_types_dormitory_id_code_key")?"รหัสค่าบริการนี้มีแล้ว":message.includes("BILLING_CYCLE_LOCKED")?"รอบบิลถูกเปิดใช้งานหรือล็อกแล้ว":message.includes("FORBIDDEN")?"คุณไม่มีสิทธิ์ดำเนินการ":"ไม่สามารถดำเนินการได้ กรุณาตรวจสอบข้อมูลอีกครั้ง";return{error:thai};};
const refresh=()=>{revalidatePath("/billing");revalidatePath("/");};
export async function createBillingCycleAction(_s:BillingActionState,f:FormData):Promise<BillingActionState>{const parsed=billingCycleSchema.safeParse(Object.fromEntries(f));if(!parsed.success)return{fieldErrors:parsed.error.flatten().fieldErrors};try{const c=await requireDormitoryContext("invoices.manage");await new BillingService(c.supabase,c).createCycle(parsed.data);refresh();return{success:true,message:"สร้างรอบบิลสำเร็จ"};}catch(e){return failure(e);}}
export async function createServiceChargeAction(_s:BillingActionState,f:FormData):Promise<BillingActionState>{const parsed=serviceChargeSchema.safeParse(Object.fromEntries(f));if(!parsed.success)return{fieldErrors:parsed.error.flatten().fieldErrors};try{const c=await requireDormitoryContext("invoices.manage");await new BillingService(c.supabase,c).createCharge(parsed.data);refresh();return{success:true,message:"เพิ่มค่าบริการสำเร็จ"};}catch(e){return failure(e);}}
export async function assignServiceChargeAction(_s:BillingActionState,f:FormData):Promise<BillingActionState>{const parsed=assignChargeSchema.safeParse(Object.fromEntries(f));if(!parsed.success)return{fieldErrors:parsed.error.flatten().fieldErrors};try{const c=await requireDormitoryContext("invoices.manage");await new BillingService(c.supabase,c).assignCharge(parsed.data);refresh();return{success:true,message:"ผูกค่าบริการกับสัญญาสำเร็จ"};}catch(e){return failure(e);}}
export async function generateInvoicesAction(_s:BillingActionState,f:FormData):Promise<BillingActionState>{const parsed=entityIdSchema.safeParse(Object.fromEntries(f));if(!parsed.success)return{error:"รอบบิลไม่ถูกต้อง"};try{const c=await requireDormitoryContext("invoices.manage");const result=await new BillingService(c.supabase,c).generate(parsed.data.id);refresh();return{success:true,message:`สร้างบิลใหม่ ${result.generated} รายการ · ข้ามรายการเดิม ${result.skipped} รายการ`};}catch(e){return failure(e);}}
export async function approveInvoiceAction(_s:BillingActionState,f:FormData):Promise<BillingActionState>{const parsed=entityIdSchema.safeParse(Object.fromEntries(f));if(!parsed.success)return{error:"ใบแจ้งหนี้ไม่ถูกต้อง"};try{const c=await requireDormitoryContext("invoices.manage");const number=await new BillingService(c.supabase,c).approve(parsed.data.id);refresh();return{success:true,message:`อนุมัติ ${number} และลง Ledger สำเร็จ`};}catch(e){return failure(e);}}
