"use client";

import { useActionState, useEffect } from "react";
import { ClipboardCheck, LoaderCircle } from "lucide-react";
import { useRouter } from "next/navigation";
import Image from "next/image";
import { saveInspectionAction } from "@/app/contracts/[id]/actions";
import { inspectionCategories, inspectionLabels, type SigningActionState } from "@/features/contracts/signature-schemas";

interface Existing { category:string; condition:string; notes:string|null }
export function InspectionForm({contractId,existing,locked,photoUrls}:{contractId:string;existing:Existing[];locked:boolean;photoUrls:string[]}) {
  const [state,action,pending]=useActionState<SigningActionState,FormData>(saveInspectionAction,{}); const router=useRouter();
  useEffect(()=>{if(state.success)router.refresh();},[router,state.success]); const byCategory=new Map(existing.map(item=>[item.category,item]));
  return <section className="rounded-xl border border-slate-200 bg-[var(--surface)] p-5"><div className="mb-4 flex items-center gap-2"><ClipboardCheck className="text-blue-700"/><div><h2 className="font-bold">แบบตรวจรับห้องก่อนเข้าอยู่</h2><p className="text-xs text-[var(--muted)]">ต้องบันทึกก่อนมีผู้ลงนาม และแนบรูปได้ไม่เกิน 5 รูปต่อครั้ง</p></div></div>{locked&&<p className="mb-4 rounded-lg bg-amber-50 p-3 text-sm text-amber-800">สัญญามีลายเซ็นแล้ว แบบตรวจรับถูกล็อกเพื่อรักษาหลักฐานเดิม</p>}<form action={action} className="space-y-4"><input type="hidden" name="contractId" value={contractId}/><div className="overflow-x-auto"><table className="w-full min-w-[620px] text-sm"><thead><tr className="border-b text-left text-slate-500"><th className="p-2">รายการ</th><th className="p-2">สภาพ</th><th className="p-2">หมายเหตุ</th></tr></thead><tbody>{inspectionCategories.map(category=>{const value=byCategory.get(category);return <tr key={category} className="border-b border-slate-100"><td className="p-2 font-medium">{inspectionLabels[category]}</td><td className="p-2"><select name={`condition_${category}`} defaultValue={value?.condition??"good"} disabled={locked} className="rounded-lg border border-slate-300 bg-transparent px-2 py-2"><option value="good">ปกติ</option><option value="damaged">ชำรุด</option><option value="missing">ไม่มี/สูญหาย</option><option value="not_applicable">ไม่มีรายการนี้</option></select></td><td className="p-2"><input name={`notes_${category}`} defaultValue={value?.notes??""} disabled={locked} className="w-full rounded-lg border border-slate-300 bg-transparent px-2 py-2"/></td></tr>})}</tbody></table></div>{photoUrls.length>0&&<div><p className="mb-2 text-sm font-medium">รูปที่บันทึกแล้ว</p><div className="grid grid-cols-3 gap-2">{photoUrls.map((url,index)=><a key={url} href={url} target="_blank" rel="noreferrer"><Image unoptimized src={url} width={300} height={96} alt={`สภาพห้อง ${index+1}`} className="h-24 w-full rounded-lg border object-cover"/></a>)}</div></div>}<label className="block text-sm font-medium">รูปสภาพห้อง (PNG/JPEG/WebP, ไม่เกิน 5 MB/รูป)<input name="inspectionPhotos" type="file" accept="image/png,image/jpeg,image/webp" multiple disabled={locked} className="mt-1.5 block w-full rounded-lg border border-slate-300 p-2 text-sm"/></label>{state.error&&<p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{state.error}</p>}{state.success&&<p className="rounded-lg bg-emerald-50 p-3 text-sm text-emerald-700">{state.message}</p>}<button disabled={pending||locked} className="flex items-center gap-2 rounded-lg bg-blue-700 px-4 py-2.5 font-semibold text-white disabled:opacity-50">{pending&&<LoaderCircle size={18} className="animate-spin"/>}บันทึกแบบตรวจรับ</button></form></section>;
}
