import Link from "next/link";
import { ArrowLeft, CheckCircle2, Download, FileText, ShieldCheck } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { SignaturePad } from "@/components/contracts/signature-pad";
import { InspectionForm } from "@/components/contracts/inspection-form";
import { generateContractDocumentAction } from "@/app/contracts/actions";
import { requireDormitoryContext } from "@/lib/auth/context";
import { relationOne } from "@/lib/supabase/relations";

export default async function ContractDetailPage({params}:{params:Promise<{id:string}>}) {
  const {id}=await params; const context=await requireDormitoryContext("contracts.manage");
  const {data:contract}=await context.supabase.from("contracts").select("id,contract_number,status,tenant_id,rooms(room_number),tenants(title,first_name,last_name)").eq("id",id).eq("dormitory_id",context.dormitoryId).single();
  if(!contract) return <AppShell><div className="p-8">ไม่พบสัญญา หรือคุณไม่มีสิทธิ์เข้าถึง</div></AppShell>;
  const [{data:document},{data:signatures},{data:inspections}]=await Promise.all([
    context.supabase.from("generated_documents").select("id,checksum").eq("entity_id",id).eq("document_type","contract").maybeSingle(),
    context.supabase.from("contract_signatures").select("id,signer_role,signer_name,signed_at,document_checksum").eq("contract_id",id).order("signed_at"),
    context.supabase.from("room_asset_inspections").select("id,category,condition,notes").eq("contract_id",id),
  ]);
  const inspectionIds=(inspections??[]).map(item=>item.id); const photoUrls:string[]=[];
  if(inspectionIds.length){const {data:attachments}=await context.supabase.from("room_inspection_attachments").select("storage_path").in("inspection_id",inspectionIds).order("created_at");for(const attachment of attachments??[]){const {data}=await context.supabase.storage.from("room-inspections").createSignedUrl(attachment.storage_path,300);if(data?.signedUrl)photoUrls.push(data.signedUrl);}}
  const tenant=relationOne(contract.tenants); const room=relationOne(contract.rooms); const tenantName=`${tenant?.title??""}${tenant?.first_name??""} ${tenant?.last_name??""}`.trim(); const signedRoles=(signatures??[]).map(item=>item.signer_role);
  return <AppShell><div className="mx-auto max-w-6xl p-4 md:p-8"><Link href="/contracts" className="mb-5 inline-flex items-center gap-1 text-sm text-teal-700"><ArrowLeft size={16}/>กลับหน้าสัญญา</Link><header className="mb-6 flex flex-wrap items-end justify-between gap-3"><div><p className="text-sm font-semibold text-teal-700">CONTRACT SIGNING</p><h1 className="text-2xl font-bold">{contract.contract_number} · ห้อง {room?.room_number}</h1><p className="text-sm text-[var(--muted)]">ผู้เช่า {tenantName}</p></div><div className="flex gap-2"><Link href={`/contracts/${id}/print`} target="_blank" className="flex items-center gap-1 rounded-lg border px-3 py-2 text-sm"><FileText size={16}/>พิมพ์ HTML</Link>{document&&<Link href={`/api/documents/${document.id}/pdf`} className="flex items-center gap-1 rounded-lg bg-teal-700 px-3 py-2 text-sm text-white"><Download size={16}/>ดาวน์โหลด PDF</Link>}</div></header>{!document?<section className="mb-5 rounded-xl border border-amber-200 bg-amber-50 p-5"><h2 className="font-bold text-amber-900">ต้องสร้าง Document Snapshot ก่อนลงนาม</h2><p className="mb-3 text-sm text-amber-800">Snapshot จะล็อกข้อความ Template และข้อมูลสัญญาฉบับนี้</p><form action={generateContractDocumentAction}><input type="hidden" name="contractId" value={id}/><button className="rounded-lg bg-amber-700 px-4 py-2 text-sm font-semibold text-white">สร้าง PDF Snapshot</button></form></section>:<section className="mb-5 rounded-xl border border-slate-200 bg-[var(--surface)] p-5"><div className="flex items-center gap-2"><ShieldCheck className="text-emerald-700"/><div><h2 className="font-bold">Document checksum</h2><code className="break-all text-xs text-slate-500">SHA-256 {document.checksum}</code></div></div><div className="mt-4 grid gap-3 sm:grid-cols-2">{["tenant","owner"].map(role=>{const signature=signatures?.find(item=>item.signer_role===role);return <div key={role} className={`rounded-lg border p-3 ${signature?"border-emerald-200 bg-emerald-50":"border-dashed"}`}>{signature?<><p className="flex items-center gap-1 font-semibold text-emerald-800"><CheckCircle2 size={16}/>ลงนามแล้ว: {signature.signer_name}</p><p className="text-xs text-emerald-700">{new Intl.DateTimeFormat("th-TH",{dateStyle:"medium",timeStyle:"medium",timeZone:"Asia/Bangkok"}).format(new Date(signature.signed_at))}</p></>:<p className="text-sm text-slate-500">รอลายเซ็น{role==="tenant"?"ผู้เช่า":"ผู้ให้เช่า"}</p>}</div>})}</div></section>}<div className="grid items-start gap-5 xl:grid-cols-2"><InspectionForm contractId={id} existing={inspections??[]} locked={signedRoles.length>0} photoUrls={photoUrls}/>{document?<SignaturePad documentId={document.id} tenantName={tenantName} ownerName="ผู้ให้เช่า" signedRoles={signedRoles}/>:<div className="rounded-xl border border-dashed p-8 text-center text-slate-500">สร้าง Snapshot ก่อนเพื่อเปิดแบบลงนาม</div>}</div></div></AppShell>;
}
